/* ETA'*/
DROP TEMPORARY TABLE IF EXISTS ETA;

CREATE TEMPORARY TABLE ETA AS
SELECT
CLIENTE.ID_CLIENTE,
TIMESTAMPDIFF(YEAR, DATA_NASCITA, CURDATE()) AS ETA
FROM BANCA.CLIENTE;

SELECT * FROM ETA;

/*NUMERO DI TRANSAZIONI IN USCITA SU TUTTI I CONTI*/
DROP TEMPORARY TABLE IF EXISTS NUM_TRANS_OUT;

CREATE TEMPORARY TABLE NUM_TRANS_OUT AS
SELECT
CLIENTE.ID_CLIENTE,
COUNT(CASE WHEN SEGNO = '-' THEN 1 ELSE NULL END) AS NUM_TRANS_OUT
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM NUM_TRANS_OUT;

/*NUMERO DI TRANSAZIONI IN ENTRATA SU TUTTI I CONTI*/
DROP TEMPORARY TABLE IF EXISTS NUM_TRANS_IN;

CREATE TEMPORARY TABLE NUM_TRANS_IN AS
SELECT
CLIENTE.ID_CLIENTE,
COUNT(CASE WHEN SEGNO = '+' THEN 1 ELSE NULL END) AS NUM_TRANS_IN
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM NUM_TRANS_IN;

/* IMPORTO TOTALE TRANSATO IN USCITA SU TUTTI I CONTI */
DROP TEMPORARY TABLE IF EXISTS IMP_TRANS_OUT;

CREATE TEMPORARY TABLE IMP_TRANS_OUT AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN SEGNO = '-' THEN IMPORTO ELSE NULL END) AS IMP_TRANS_OUT
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM IMP_TRANS_OUT;

/* IMPORTO TOTALE TRANSATO IN ENTRATA SU TUTTI I CONTI */
DROP TEMPORARY TABLE IF EXISTS IMP_TRANS_IN;

CREATE TEMPORARY TABLE IMP_TRANS_IN AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN SEGNO = '+' THEN IMPORTO ELSE NULL END) AS IMP_TRANS_IN
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM IMP_TRANS_IN;

/* NUMERO TOTALE DI CONTI POSSEDUTI */
DROP TEMPORARY TABLE IF EXISTS COUNT_ID_CONTO;

CREATE TEMPORARY TABLE COUNT_ID_CONTO AS
SELECT 
CLIENTE.ID_CLIENTE,
COUNT(ID_CONTO) AS COUNT_ID_CONTO
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
GROUP BY 1;

SELECT * FROM COUNT_ID_CONTO;

/* NUMERO DI CONTI POSSEDUTI PER TIPOLOGIA */
DROP TEMPORARY TABLE IF EXISTS TIPO_CONTO;

CREATE TEMPORARY TABLE TIPO_CONTO AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN ID_TIPO_CONTO = 0 THEN 1 ELSE 0 END) AS TIPO_CONTO_BASE,
SUM(CASE WHEN ID_TIPO_CONTO = 1 THEN 1 ELSE 0 END) AS TIPO_CONTO_BUSINESS,
SUM(CASE WHEN ID_TIPO_CONTO = 2 THEN 1 ELSE 0 END) AS TIPO_CONTO_PRIVATI,
SUM(CASE WHEN ID_TIPO_CONTO = 3 THEN 1 ELSE 0 END) AS TIPO_CONTO_FAMIGLIE
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
GROUP BY 1;

SELECT * FROM TIPO_CONTO;

/* NUMERO DI TRANSAZIONI IN USCITA PER TIPOLOGIA DI CONTO */
DROP TEMPORARY TABLE IF EXISTS NUM_TRANS_OUT_PER_TIPO_CONTO;

CREATE TEMPORARY TABLE NUM_TRANS_OUT_PER_TIPO_CONTO AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN ID_TIPO_TRANS IN (3, 4, 5, 6, 7) AND CONTO.ID_TIPO_CONTO = 0 THEN 1 ELSE 0 END) AS NUM_OUT_CONTO_BASE,
SUM(CASE WHEN ID_TIPO_TRANS IN (3, 4, 5, 6, 7) AND CONTO.ID_TIPO_CONTO = 1 THEN 1 ELSE 0 END) AS NUM_OUT_CONTO_BUSINESS,
SUM(CASE WHEN ID_TIPO_TRANS IN (3, 4, 5, 6, 7) AND CONTO.ID_TIPO_CONTO = 2 THEN 1 ELSE 0 END) AS NUM_OUT_CONTO_PRIVATI,
SUM(CASE WHEN ID_TIPO_TRANS IN (3, 4, 5, 6, 7) AND CONTO.ID_TIPO_CONTO = 3 THEN 1 ELSE 0 END) AS NUM_OUT_CONTO_FAMIGLIE
FROM BANCA.CLIENTE AS CLIENTE
LEFT JOIN BANCA.CONTO AS CONTO 
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI AS TRANS 
ON CONTO.ID_CONTO = TRANS.ID_CONTO
GROUP BY CLIENTE.ID_CLIENTE;

SELECT * FROM NUM_TRANS_OUT_PER_TIPO_CONTO;

/* NUMERO DI TRANSAZIONI IN ENTRATA PER TIPOLOGIA DI CONTO */
DROP TEMPORARY TABLE IF EXISTS NUM_TRANS_IN_PER_TIPO_CONTO;

CREATE TEMPORARY TABLE NUM_TRANS_IN_PER_TIPO_CONTO AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN ID_TIPO_TRANS IN (0, 1, 2) AND CONTO.ID_TIPO_CONTO = 0 THEN 1 ELSE 0 END) AS NUM_IN_CONTO_BASE,
SUM(CASE WHEN ID_TIPO_TRANS IN (0, 1, 2) AND CONTO.ID_TIPO_CONTO = 1 THEN 1 ELSE 0 END) AS NUM_IN_CONTO_BUSINESS,
SUM(CASE WHEN ID_TIPO_TRANS IN (0, 1, 2) AND CONTO.ID_TIPO_CONTO = 2 THEN 1 ELSE 0 END) AS NUM_IN_CONTO_PRIVATI,
SUM(CASE WHEN ID_TIPO_TRANS IN (0, 1, 2) AND CONTO.ID_TIPO_CONTO = 3 THEN 1 ELSE 0 END) AS NUM_IN_CONTO_FAMIGLIE
FROM BANCA.CLIENTE AS CLIENTE
LEFT JOIN BANCA.CONTO AS CONTO 
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI AS TRANS 
ON CONTO.ID_CONTO = TRANS.ID_CONTO
GROUP BY CLIENTE.ID_CLIENTE;

SELECT * FROM NUM_TRANS_IN_PER_TIPO_CONTO;

/* IMPORTO TRANSATO IN USCITA PER TIPOLOGIA DI CONTO */
DROP TEMPORARY TABLE IF EXISTS TIPO_IMP_OUT;

CREATE TEMPORARY TABLE TIPO_IMP_OUT AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN SEGNO = '-' AND ID_TIPO_CONTO = 0 THEN IMPORTO ELSE 0 END) AS IMP_OUT_CONTO_BASE,
SUM(CASE WHEN SEGNO = '-' AND ID_TIPO_CONTO = 1 THEN IMPORTO ELSE 0 END) AS IMP_OUT_CONTO_BUSINESS,
SUM(CASE WHEN SEGNO = '-' AND ID_TIPO_CONTO = 2 THEN IMPORTO ELSE 0 END) AS IMP_OUT_CONTO_PRIVATI,
SUM(CASE WHEN SEGNO = '-' AND ID_TIPO_CONTO = 3 THEN IMPORTO ELSE 0 END) AS IMP_OUT_CONTO_FAMIGLIE
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM TIPO_IMP_OUT;

/* IMPORTO TRANSATO IN ENTRATA PER TIPOLOGIA DI CONTO */
DROP TEMPORARY TABLE IF EXISTS TIPO_IMP_IN;

CREATE TEMPORARY TABLE TIPO_IMP_IN AS
SELECT 
CLIENTE.ID_CLIENTE,
SUM(CASE WHEN SEGNO = '+' AND ID_TIPO_CONTO = 0 THEN IMPORTO ELSE 0 END) AS IMP_IN_CONTO_BASE,
SUM(CASE WHEN SEGNO = '+' AND ID_TIPO_CONTO = 1 THEN IMPORTO ELSE 0 END) AS IMP_IN_CONTO_BUSINESS,
SUM(CASE WHEN SEGNO = '+' AND ID_TIPO_CONTO = 2 THEN IMPORTO ELSE 0 END) AS IMP_IN_CONTO_PRIVATI,
SUM(CASE WHEN SEGNO = '+' AND ID_TIPO_CONTO = 3 THEN IMPORTO ELSE 0 END) AS IMP_IN_CONTO_FAMIGLIE
FROM BANCA.CLIENTE CLIENTE
LEFT JOIN BANCA.CONTO CONTO
ON CLIENTE.ID_CLIENTE = CONTO.ID_CLIENTE
LEFT JOIN BANCA.TRANSAZIONI TRANS
ON CONTO.ID_CONTO = TRANS.ID_CONTO
LEFT JOIN BANCA.TIPO_TRANSAZIONE AS TIPO_TRANS
ON TRANS.ID_TIPO_TRANS = TIPO_TRANS.ID_TIPO_TRANSAZIONE
GROUP BY 1;

SELECT * FROM TIPO_IMP_IN;

/*TABELLA FINALE DENORMALIZZATA*/
DROP TABLE IF EXISTS FINAL_TABLE;

CREATE TABLE FINAL_TABLE AS
SELECT
ETA.*,
NUM_TRANS_OUT.NUM_TRANS_OUT,
NUM_TRANS_IN.NUM_TRANS_IN,
IMP_TRANS_OUT.IMP_TRANS_OUT,
IMP_TRANS_IN.IMP_TRANS_IN,
COUNT_ID_CONTO.COUNT_ID_CONTO,
TIPO_CONTO.TIPO_CONTO_BASE,TIPO_CONTO_BUSINESS,TIPO_CONTO_PRIVATI,TIPO_CONTO_FAMIGLIE,
NUM_TRANS_OUT_PER_TIPO_CONTO.NUM_OUT_CONTO_BASE,NUM_OUT_CONTO_BUSINESS,NUM_OUT_CONTO_PRIVATI,NUM_OUT_CONTO_FAMIGLIE,
NUM_TRANS_IN_PER_TIPO_CONTO.NUM_IN_CONTO_BASE,NUM_IN_CONTO_BUSINESS,NUM_IN_CONTO_PRIVATI,NUM_IN_CONTO_FAMIGLIE,
TIPO_IMP_OUT.IMP_OUT_CONTO_BASE,IMP_OUT_CONTO_BUSINESS,IMP_OUT_CONTO_PRIVATI,IMP_OUT_CONTO_FAMIGLIE,
TIPO_IMP_IN.IMP_IN_CONTO_BASE,IMP_IN_CONTO_BUSINESS,IMP_IN_CONTO_PRIVATI,IMP_IN_CONTO_FAMIGLIE
FROM ETA
JOIN NUM_TRANS_OUT ON ETA.ID_CLIENTE = NUM_TRANS_OUT.ID_CLIENTE
JOIN NUM_TRANS_IN ON ETA.ID_CLIENTE = NUM_TRANS_IN.ID_CLIENTE
JOIN IMP_TRANS_OUT ON ETA.ID_CLIENTE = IMP_TRANS_OUT.ID_CLIENTE
JOIN IMP_TRANS_IN ON ETA.ID_CLIENTE = IMP_TRANS_IN.ID_CLIENTE
JOIN COUNT_ID_CONTO ON ETA.ID_CLIENTE = COUNT_ID_CONTO.ID_CLIENTE
JOIN TIPO_CONTO ON ETA.ID_CLIENTE = TIPO_CONTO.ID_CLIENTE
JOIN NUM_TRANS_OUT_PER_TIPO_CONTO ON ETA.ID_CLIENTE = NUM_TRANS_OUT_PER_TIPO_CONTO.ID_CLIENTE
JOIN NUM_TRANS_IN_PER_TIPO_CONTO ON ETA.ID_CLIENTE = NUM_TRANS_IN_PER_TIPO_CONTO.ID_CLIENTE
JOIN TIPO_IMP_OUT ON ETA.ID_CLIENTE = TIPO_IMP_OUT.ID_CLIENTE
JOIN TIPO_IMP_IN ON ETA.ID_CLIENTE = TIPO_IMP_IN.ID_CLIENTE;

SELECT * FROM FINAL_TABLE;
